### PR TITLE
Parse text in stream & handle execution_count when null

### PR DESCRIPTION
**Pull request by Wuvist**
Hi~

Thanks for this package.

I'm new to OCaml, not sure if these two small fixes are done properly. If so, I will try to send more PR ^_^

### CODE REVIEW

**Comment by dermesser** [comment]
There appears to be a failing test; would you mind taking another look at it?

**Comment by dermesser** [comment]
specifically it appears that the `text` field might be either a list or a plain string, depending on who produced the notebook- so instead of only handling a string list, you'd need to handle both cases. It's not pretty but `extract_or` can probably help.

**Comment by Wuvist** [comment]
Hi @dermesser I pushed two more commit

45512f5226832a92c4a27ba986d6af12189fa65c Will try extract as string list first, if failed, then extract as string.
(I can't figure out how to use `extract_or`)

I'm not sure why the filename hash for attachment are changed. In ceaf1b49b3e9a60384f87661489af7e346d915d9 I just change them to the new hash to pass the test. Please let me know if this is the wrong approach.

Thanks, it's fun for me to learn some OCaml, and utilise it with typst :)

**Comment by dermesser** [comment]
the problem with the filenames is that they're randomly generated. For some reason this appears to work, probably the random generator receives the same seed at the start of the test run, and the CI now fails again (the previous file names were good?)

**Comment by Wuvist** [comment]
Thanks for merging.

I figure out why the filename hash are different: I used a different OCaml compiler version - 4.14.1

After switch to 5.0.0 as specified in workflow.yml, my local env generate the same filename hash.

**Pull request merged**
